# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e681e9cd1801227d1e225191d7279356f78e1412eed5fbba810e3243488211a528276e72d00a8fce116ec1deaf943c1ede4d02c293e2e506289c9a08e374a51f

test:
  secret_key_base: 6f4787dc1440d0f92576640404e32e6a0a748cf6ad6aa0db91045bc71b24006d69a634591cde846d577c5cabf5eea65c88a66ee97a6c2ca225e6b01a3904ec8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
